dist: xenial   # required for Python >= 3.7
language: python

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.2
      - python3.3

matrix:
  include:
      env: TOXENV=flake8
    - python: 2.7
      env: TOXENV=py32
    - python: 2.7
      env: TOXENV=py33
    - python: 2.7
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: pypy
      env: TOXENV=pypy

python:
  - 3.7
  - "3.8-dev"

install:
  - pip install -U setuptools;
    python setup.py install;
    pip install pytest-cov;

script:
  - tox

notifications:
  email:
    - shuntingyard@gmail.com
